### ISSUE TITLE
Error: Cannot find module 'lerna/lib/PackageUtilities'

### ISSUE THREAD

**Issue by zivl** [wix/lerna-script#133]
I followed the instructions on README files, but when running the `deps:sync` task, I get this error:
```
> lerna-script "deps:sync"

internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'lerna/lib/PackageUtilities'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/user/github/experts/node_modules/lerna-script/lib/iterators.js:1:88)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
```

**Comment by viliusl** [comment]
Hi, `lerna-script` currently supports only lerna 2.x.x and not 3.x.x. Work is in progress to release version supporting 3.x.x, but lerna went major restructuring so need to think on how to do that

**Comment by hugebdu** [comment]
> Work is in progress to release version supporting 3.x.x

what's the progress status, Sir?
